#!/bin/sh

file="$HOME/.config/.todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a task: "

cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file" -nb "#1a1826" -nf "#6e6c7e" -sf "#000000" -sb "#96cdfb" -fn "Andika-10" -i)
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file" -nb "#1a1826" -nf "#6e6c7e" -sf "#1a1826" -sb "#96cdfb" -fn "Andika-10" -i)
done

exit 0
